apiVersion: v1
kind: Service
metadata:
  name: event-scheduler-cluster
  labels:
    app: event-scheduler
spec:
  ports:
    - port: 5559
      name: cluster
  clusterIP: None
  selector:
    app: event-scheduler
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: event-scheduler
  name: event-scheduler
spec:
  serviceName: event-scheduler-cluster
  replicas: 3
  selector:
    matchLabels:
      app: event-scheduler
  template:
    metadata:
      labels:
        app: event-scheduler
    spec:
      containers:
        - image: maxmtmn/event-scheduler:latest
          name: event-scheduler
          imagePullPolicy: IfNotPresent
          resources: {}
          env:
            - name: LOG_LEVEL
              value: info
            - name: LISTENER_DRIVER
              value: pubsub
            - name: PUBSUB_LISTENER_PROJECT_ID
              value: YOUR_SOURCE_GOOGLE_PROJECT
            - name: PUBSUB_LISTENER_SUBSCRIPTION_ID
              value: YOUR_SOURCE_SUBSCRIPTION
            - name: PUBSUB_LISTENER_KEY_FILE
              value: key.json
            - name: PUBLISHER_DRIVER
              value: pubsub
            - name: PUBSUB_PUBLISHER_PROJECT_ID
              value: YOUR_TARGET_GOOGLE_PROJECT
            - name: PUBSUB_PUBLISHER_TOPIC_ID
              value: YOUR_TARGET_TOPIC
            - name: PUBSUB_PUBLISHER_KEY_FILE
              value: key.json
            - name: STORAGE_PATH
              value: /data
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NODE_HOST
              value: "$(NODE_NAME).event-scheduler-cluster.default.svc.cluster.local"
            - name: CLUSTER_NODE_PORT
              value: "5559"
            - name: CLUSTER_INITIAL_NODES
              value: "event-scheduler-0.event-scheduler-cluster.default.svc.cluster.local:5559,event-scheduler-1.event-scheduler-cluster.default.svc.cluster.local:5559,event-scheduler-2.event-scheduler-cluster.default.svc.cluster.local:5559"
          volumeMounts:
            - name: keyfile
              subPath: key.json
              mountPath: /key.json
              readOnly: true
            - name: storage
              mountPath: /data
      volumes:
        - name: keyfile
          secret:
            secretName: pubsubserviceaccount
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "default"
        resources:
          requests:
            storage: 2Gi